mysql:
  local:
    host: localhost
    port: 3306
    db: peagym
    user: root
    password: 12345678
  prod:
    host: prod_db
    port: 3306
    db: peacock
    user: user
    password: strong_pass
